### ISSUE TITLE
CryptoModule.CryptoContainerDeserializer can't handle multiple CryptoContainer fields

### ISSUE THREAD

**Issue by DanielGronau** [prisma-capacity/cryptoshred#152]
When having multiple CryptoContainer fields with different generic types in one JSON object, CryptoModule.CryptoContainerDeserializer throws an error indicating that it assigned the wrong generic type to a field.

**Comment by uweschaefer** [comment]
closed by #153

**Comment by uweschaefer** [comment]
released and pushed to central as 1.1.1
