### ISSUE TITLE
Autoconfiguration issue

### ISSUE THREAD

**Issue by maciekpapiez** [prisma-capacity/cryptoshred#290]
Dear all,

Is there any specific reason why `AWSDynamoDBKeyRepositoryConfiguration` doesn't have `@ConditionalOnMissingBean` applied? This forced us to use `@Primary` on a in-memory bean definition.

Thanks in advance for any feedback.

**Comment by uweschaefer** [comment]
Nope, no good reason i see here. Would you provide a PR?

**Comment by maciekpapiez** [comment]
Sure, will do @uweschaefer :)

**Comment by uweschaefer** [comment]
if you're quick, you'll get it into the pending release @maciekpapiez

**Comment by uweschaefer** [comment]
kidding, just adding it.

**Comment by maciekpapiez** [comment]
Many thanks!

**Comment by uweschaefer** [comment]
released with 1.1.5 @maciekpapiez
